import type { ProjectRecommendation } from '../types';

export function exportJSONLines(projects: ProjectRecommendation[]): string {
  return projects.map(p => JSON.stringify(p)).join('\n');
}

export function exportMarkdownTable(projects: ProjectRecommendation[]): string {
  const headers = ['Repository', 'Score', 'Grade', 'Track', 'Language', 'Stars'];
  const rows = projects.map(p => [
    `[${p.repo.fullName}](${p.repo.htmlUrl})`,
    p.totalScore.toFixed(1),
    p.grade,
    p.track,
    p.repo.language || '-',
    (p.repo.stargazersCount || 0).toLocaleString(),
  ]);

  const headerRow = `| ${headers.join(' | ')} |`;
  const separatorRow = `| ${headers.map(() => '---').join(' | ')} |`;
  const dataRows = rows.map(r => `| ${r.join(' | ')} |`).join('\n');

  return `${headerRow}\n${separatorRow}\n${dataRows}`;
}

export function exportHTMLReport(projects: ProjectRecommendation[], title: string = 'Ralph Evaluation Report'): string {
  const tableRows = projects.map(p => `
    <tr>
      <td><a href="${p.repo.htmlUrl}">${p.repo.fullName}</a></td>
      <td>${p.totalScore.toFixed(1)}</td>
      <td>${p.grade}</td>
      <td>${p.track}</td>
      <td>${p.repo.language || '-'}</td>
      <td>${(p.repo.stargazersCount || 0).toLocaleString()}</td>
    </tr>
  `).join('');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 1200px; margin: 0 auto; padding: 20px; background: #0f0f0f; color: #e5e5e5; }
    h1 { color: #8b5cf6; }
    table { width: 100%; border-collapse: collapse; margin-top: 20px; }
    th, td { padding: 12px; text-align: left; border-bottom: 1px solid #333; }
    th { background: #1a1a1a; color: #a78bfa; }
    tr:hover { background: #1a1a1a; }
    a { color: #8b5cf6; text-decoration: none; }
    a:hover { text-decoration: underline; }
    .meta { color: #666; font-size: 14px; margin-top: 20px; }
  </style>
</head>
<body>
  <h1>${title}</h1>
  <p class="meta">Generated by Ralph on ${new Date().toLocaleDateString()} | ${projects.length} projects</p>
  <table>
    <thead>
      <tr><th>Repository</th><th>Score</th><th>Grade</th><th>Track</th><th>Language</th><th>Stars</th></tr>
    </thead>
    <tbody>${tableRows}</tbody>
  </table>
</body>
</html>`;
}

export function downloadFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
