import React, { useCallback } from 'react';
import type { ProjectRecommendation } from '../types';

interface PDFExportProps {
  projects: ProjectRecommendation[];
  query: string;
}

const PDFExport: React.FC<PDFExportProps> = ({ projects, query }) => {
  const exportPDF = useCallback(() => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) {
      alert('请允许弹出窗口以导出 PDF');
      return;
    }

    const gradeColors: Record<string, string> = {
      S: '#8b5cf6',
      A: '#3b82f6',
      B: '#10b981',
      X: '#6b7280',
    };

    const trackLabels: Record<string, string> = {
      neglected: '被忽视',
      'high-star': '高星',
      steady: '稳态',
    };

    const rows = projects
      .map(
        (p) => `
      <tr>
        <td style="padding:8px;border:1px solid #e5e7eb;font-size:11px;">
          <div style="font-weight:600;">${p.repo.fullName}</div>
          <div style="color:#6b7280;font-size:10px;">${p.repo.description || ''}</div>
        </td>
        <td style="padding:8px;border:1px solid #e5e7eb;text-align:center;font-size:11px;">
          <span style="background:${gradeColors[p.grade]};color:#fff;padding:2px 6px;border-radius:4px;font-weight:bold;">${p.grade}</span>
          <div style="margin-top:2px;">${p.totalScore.toFixed(1)}</div>
        </td>
        <td style="padding:8px;border:1px solid #e5e7eb;text-align:center;font-size:11px;">
          ${trackLabels[p.track]}
        </td>
        <td style="padding:8px;border:1px solid #e5e7eb;text-align:center;font-size:11px;">
          ${p.recommendationIndex.toFixed(2)}
        </td>
        <td style="padding:8px;border:1px solid #e5e7eb;text-align:center;font-size:11px;">
          ${p.repo.stargazersCount}
        </td>
        <td style="padding:8px;border:1px solid #e5e7eb;text-align:center;font-size:11px;">
          ${p.evidenceLevel}
        </td>
        <td style="padding:8px;border:1px solid #e5e7eb;text-align:center;font-size:11px;">
          ${
            p.dimensions
              ?.map((d) => `${d.dimension}:${d.score}/${d.maxScore}`)
              .join('<br>') || ''
          }
        </td>
      </tr>`
      )
      .join('');

    const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>Ralph 评定报告 - ${query}</title>
  <style>
    @page { size: A4 landscape; margin: 15mm; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; margin: 0; padding: 0; color: #111827; }
    .header { display:flex; align-items:center; justify-content:space-between; padding:16px 24px; border-bottom:2px solid #8b5cf6; }
    .header h1 { margin:0; font-size:18px; color:#8b5cf6; }
    .header .meta { font-size:11px; color:#6b7280; }
    .summary { display:flex; gap:24px; padding:12px 24px; background:#f9fafb; border-bottom:1px solid #e5e7eb; }
    .summary .item { text-align:center; }
    .summary .item .value { font-size:20px; font-weight:bold; color:#8b5cf6; }
    .summary .item .label { font-size:10px; color:#6b7280; }
    table { width:100%; border-collapse:collapse; margin-top:12px; }
    th { background:#f3f4f6; padding:8px; border:1px solid #e5e7eb; font-size:11px; text-align:left; color:#374151; }
    .footer { padding:12px 24px; border-top:1px solid #e5e7eb; font-size:9px; color:#9ca3af; text-align:center; }
    @media print { body { -webkit-print-color-adjust: exact; print-color-adjust: exact; } }
  </style>
</head>
<body>
  <div class="header">
    <h1>Ralph GitHub Project Evaluator</h1>
    <div class="meta">
      查询: ${query}<br/>
      生成时间: ${new Date().toLocaleString('zh-CN')}<br/>
      项目数: ${projects.length}
    </div>
  </div>
  <div class="summary">
    <div class="item"><div class="value">${projects.filter(p => p.grade === 'S').length}</div><div class="label">S 级</div></div>
    <div class="item"><div class="value">${projects.filter(p => p.grade === 'A').length}</div><div class="label">A 级</div></div>
    <div class="item"><div class="value">${projects.filter(p => p.grade === 'B').length}</div><div class="label">B 级</div></div>
    <div class="item"><div class="value">${(projects.reduce((s, p) => s + p.totalScore, 0) / (projects.length || 1)).toFixed(1)}</div><div class="label">平均分</div></div>
    <div class="item"><div class="value">${projects.reduce((m, p) => Math.max(m, p.recommendationIndex), 0).toFixed(2)}</div><div class="label">最高推荐指数</div></div>
  </div>
  <table>
    <thead>
      <tr>
        <th style="width:28%;">项目</th>
        <th style="width:8%;">等级</th>
        <th style="width:8%;">轨道</th>
        <th style="width:10%;">推荐指数</th>
        <th style="width:8%;">Stars</th>
        <th style="width:6%;">证据</th>
        <th style="width:32%;">六维评分</th>
      </tr>
    </thead>
    <tbody>
      ${rows}
    </tbody>
  </table>
  <div class="footer">
    Generated by Ralph - GitHub 高质量项目发现与评估工具 | 评定规则 v3.2 | 本报告仅供参考
  </div>
</body>
</html>`;

    printWindow.document.write(html);
    printWindow.document.close();
    printWindow.onload = () => {
      printWindow.print();
    };
  }, [projects, query]);

  if (projects.length === 0) return null;

  return (
    <button
      onClick={exportPDF}
      className="text-xs px-2.5 py-1 rounded border border-gray-700 text-gray-400 hover:text-gray-300 hover:bg-gray-800 transition-colors flex items-center gap-1"
      title="导出 PDF 报告"
    >
      <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 21h10a2 2 0 002-2V9.414a1 1 0 00-.293-.707l-5.414-5.414A1 1 0 0012.586 3H7a2 2 0 00-2 2v14a2 2 0 002 2z" />
      </svg>
      PDF 报告
    </button>
  );
};

export default PDFExport;
